default_stages: [commit]

repos:
    - repo: meta
      hooks:
          - id: check-hooks-apply

          - id: check-useless-excludes

    - repo: local
      hooks:
          - id: build-slides
            name: Build slides
            language: system
            files: slides.(md|html)
            pass_filenames: false
            entry: pnpm build
