name: "Pre-commit: autoupdate"

on:
  # every monday at midnight
  schedule:
    - cron: "0 0 * * 1"

jobs:
  auto-update:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
      - run: pnpm install --frozen-lockfile

      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - run: pip install pre-commit
      - run: pre-commit autoupdate
      - run: pre-commit run --all

      - uses: peter-evans/create-pull-request@v4
        if: always() # So we have a PR to fix manually.
        with:
          token: ${{ secrets.PAT }}
          branch: update/pre-commit-hooks
          assignees: pkoch
          title: 🔄 Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: This is a GitHub workflow (`.github/workflows/pre-commit-update.yml`) running periodically to update our pre-commit hooks' versions to their latest version.
