name: "Pre-commit: check"

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm install
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files
