name: "Pre-commit: check"

on:
  push:
    branches: [master]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
