name: "Pre-commit: check"

on:
  push:
    branches: [master]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
      - run: pnpm install
      - run: pnpm run build
      - run: git diff --text --word-diff
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files
